package de.rwhtaachen.kohlekompass.ui.theme

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF008B4F)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE8F7EE)
val md_theme_light_onPrimaryContainer = Color(0xFF6EB998)
val md_theme_light_secondary = Color(0xFFFFC700)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDC81)
val md_theme_light_onSecondaryContainer = Color(0xFF241A00)
val md_theme_light_tertiary = Color(0xFF1A5FAA)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD5E3FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001C3B)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF5FFF3)
val md_theme_light_onBackground = Color(0xFF00210E)
val md_theme_light_surface = Color(0xFFF5FFF3)
val md_theme_light_onSurface = Color(0xFF00210E)
val md_theme_light_surfaceVariant = Color(0xFFDCE5DB)
val md_theme_light_onSurfaceVariant = Color(0xFF414942)
val md_theme_light_outline = Color(0xFF717971)
val md_theme_light_inverseOnSurface = Color(0xFFC2FFD0)
val md_theme_light_inverseSurface = Color(0xFF00391C)
val md_theme_light_inversePrimary = Color(0xFF7BDA9D)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006D3E)
val md_theme_light_outlineVariant = Color(0xFFC0C9BF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF7BDA9D)
val md_theme_dark_onPrimary = Color(0xFF00391D)
val md_theme_dark_primaryContainer = Color(0xFF00522D)
val md_theme_dark_onPrimaryContainer = Color(0xFF97F7B7)
val md_theme_dark_secondary = Color(0xFFF2C000)
val md_theme_dark_onSecondary = Color(0xFF3D2F00)
val md_theme_dark_secondaryContainer = Color(0xFF584400)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFE08E)
val md_theme_dark_tertiary = Color(0xFFA7C8FF)
val md_theme_dark_onTertiary = Color(0xFF003060)
val md_theme_dark_tertiaryContainer = Color(0xFF004788)
val md_theme_dark_onTertiaryContainer = Color(0xFFD5E3FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF00210E)
val md_theme_dark_onBackground = Color(0xFF99F7B5)
val md_theme_dark_surface = Color(0xFF00210E)
val md_theme_dark_onSurface = Color(0xFF99F7B5)
val md_theme_dark_surfaceVariant = Color(0xFF414942)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C9BF)
val md_theme_dark_outline = Color(0xFF8B938A)
val md_theme_dark_inverseOnSurface = Color(0xFF00210E)
val md_theme_dark_inverseSurface = Color(0xFF99F7B5)
val md_theme_dark_inversePrimary = Color(0xFF006D3E)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF7BDA9D)
val md_theme_dark_outlineVariant = Color(0xFF414942)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF7ABE90)